name: axes_server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.2.0
  build_runner: ^2.10.5
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^3.3.1
  dotenv: ^4.2.0
  freezed: ^3.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  json_serializable: ^6.12.0
  mongo_dart: ^0.10.6
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
